export const INTEREST_DATA = [
  {
    id: 1,
    name: "Savannah Nguyen",
    email: "dolores.chambers@example.com",
    departure: "2026-04-30",
    direction: "NYC → Tampa",
    type: "One Way",
    passengers: 4,
    status: "Interested",
  },
  {
    id: 2,
    name: "Jane Cooper",
    email: "sara.cruz@example.com",
    departure: "2026-04-27",
    direction: "NYC → Tampa",
    type: "Round Trip",
    passengers: 6,
    status: "Interested",
  },
  {
    id: 3,
    name: "Courtney Henry",
    email: "alma.lawson@example.com",
    departure: "2026-04-28",
    direction: "Tampa → NYC",
    type: "One Way",
    passengers: 2,
    status: "Interested",
  },
  {
    id: 4,
    name: "Jenny Wilson",
    email: "dolores.chambers@example.com",
    departure: "2026-04-28",
    direction: "NYC → Tampa",
    type: "Round Trip",
    passengers: 4,
    status: "Interested",
  },
  {
    id: 5,
    name: "Wade Warren",
    email: "bill.sanders@example.com",
    departure: "2026-04-28",
    direction: "Tampa → NYC",
    type: "Round Trip",
    passengers: 1,
    status: "Interested",
  },
  {
    id: 6,
    name: "Jerome Bell",
    email: "dolores.chambers@example.com",
    departure: "2026-04-28",
    direction: "Tampa → NYC",
    type: "One Way",
    passengers: 1,
    status: "Interested",
  },
  {
    id: 7,
    name: "Jenny Wilson",
    email: "dolores.chambers@example.com",
    departure: "2026-04-28",
    direction: "NYC → Tampa",
    type: "Round Trip",
    passengers: 4,
    status: "Interested",
  },
  {
    id: 8,
    name: "Wade Warren",
    email: "bill.sanders@example.com",
    departure: "2026-04-28",
    direction: "Tampa → NYC",
    type: "Round Trip",
    passengers: 1,
    status: "Interested",
  },
  {
    id: 9,
    name: "Jerome Bell",
    email: "dolores.chambers@example.com",
    departure: "2026-04-28",
    direction: "Tampa → NYC",
    type: "One Way",
    passengers: 1,
    status: "Interested",
  },
];
